// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25ZJJjGarhG1_wPaFeQa6x1eRkbd1qUc',
    appId: '1:926638809954:web:847a762bdeb29bead2023b',
    messagingSenderId: '926638809954',
    projectId: 'testapp-704e6',
    authDomain: 'testapp-704e6.firebaseapp.com',
    databaseURL: 'https://testapp-704e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testapp-704e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYH2fq1qvisKoLWBPIvJ55qUgSiwPfPTM',
    appId: '1:926638809954:android:eb9edc218d90323ed2023b',
    messagingSenderId: '926638809954',
    projectId: 'testapp-704e6',
    databaseURL: 'https://testapp-704e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testapp-704e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4-XWpfGxDW1QAYmWrUutpd_Mf0Atiuc',
    appId: '1:926638809954:ios:bd8361b753b52613d2023b',
    messagingSenderId: '926638809954',
    projectId: 'testapp-704e6',
    databaseURL: 'https://testapp-704e6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'testapp-704e6.appspot.com',
    iosClientId: '926638809954-9kctcqda186gmld6ea30k7f99fmjh2bn.apps.googleusercontent.com',
    iosBundleId: 'com.management.adminapp',
  );
}
